# Generated by Django 3.0.9 on 2020-08-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0004_auto_20200804_0438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
